// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("../Utils.js");
var Styles = require("../Styles.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var Primatives$StyledFunctors = require("styled-functors/re/Primatives.js");
var TouchableOpacity$BsReactNative = require("bs-react-native/src/components/touchableOpacity.js");

var opacity = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.width(/* Pct */Block.__(1, [100])),
      /* :: */[
        Style$BsReactNative.height(/* Pct */Block.__(1, [100])),
        /* [] */0
      ]
    ]);

var buttonText = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.color(/* String */Block.__(0, [Styles.Palatte[/* white */1]])),
      /* :: */[
        Style$BsReactNative.display(/* Flex */0),
        /* :: */[
          Style$BsReactNative.justifyContent(/* Center */2),
          /* :: */[
            Style$BsReactNative.alignItems(/* Center */2),
            /* :: */[
              Style$BsReactNative.textAlign(/* Center */3),
              /* :: */[
                Style$BsReactNative.height(/* Pct */Block.__(1, [100])),
                /* :: */[
                  Style$BsReactNative.width(/* Pct */Block.__(1, [100])),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var button = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, [Styles.Palatte[/* black */2]])),
      /* :: */[
        Style$BsReactNative.borderWidth(2),
        /* :: */[
          Style$BsReactNative.borderRadius(6),
          /* :: */[
            Style$BsReactNative.width(/* Pct */Block.__(1, [70])),
            /* :: */[
              Style$BsReactNative.height(/* Pt */Block.__(0, [40])),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var buttonTextSecondary = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.color(/* String */Block.__(0, [Styles.Palatte[/* black */2]])),
      /* :: */[
        Style$BsReactNative.display(/* Flex */0),
        /* :: */[
          Style$BsReactNative.justifyContent(/* Center */2),
          /* :: */[
            Style$BsReactNative.alignItems(/* Center */2),
            /* :: */[
              Style$BsReactNative.textAlign(/* Center */3),
              /* :: */[
                Style$BsReactNative.height(/* Pct */Block.__(1, [100])),
                /* :: */[
                  Style$BsReactNative.width(/* Pct */Block.__(1, [100])),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var buttonSecondary = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.borderWidth(2),
      /* :: */[
        Style$BsReactNative.borderColor(/* String */Block.__(0, [Styles.Palatte[/* black */2]])),
        /* :: */[
          Style$BsReactNative.borderRadius(6),
          /* :: */[
            Style$BsReactNative.width(/* Pct */Block.__(1, [70])),
            /* :: */[
              Style$BsReactNative.height(/* Pt */Block.__(0, [40])),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var S = /* module */[
  /* opacity */opacity,
  /* buttonText */buttonText,
  /* button */button,
  /* buttonTextSecondary */buttonTextSecondary,
  /* buttonSecondary */buttonSecondary
];

var component = ReasonReact.statelessComponent("Button");

function make(_children, onPress, title) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                              undefined,
                              undefined,
                              undefined,
                              /* center */98248149,
                              undefined,
                              undefined,
                              Js_primitive.some(button),
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              /* array */[ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(opacity), undefined, onPress, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(buttonText), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils.str(title)]))]))]
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var component$1 = ReasonReact.statelessComponent("ButtonSecondary");

function make$1(_children, onPress, title) {
  return /* record */[
          /* debugName */component$1[/* debugName */0],
          /* reactClassInternal */component$1[/* reactClassInternal */1],
          /* handedOffState */component$1[/* handedOffState */2],
          /* willReceiveProps */component$1[/* willReceiveProps */3],
          /* didMount */component$1[/* didMount */4],
          /* didUpdate */component$1[/* didUpdate */5],
          /* willUnmount */component$1[/* willUnmount */6],
          /* willUpdate */component$1[/* willUpdate */7],
          /* shouldUpdate */component$1[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                              undefined,
                              undefined,
                              undefined,
                              /* center */98248149,
                              undefined,
                              undefined,
                              Js_primitive.some(buttonSecondary),
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              /* array */[ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(opacity), undefined, onPress, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(buttonTextSecondary), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[Utils.str(title)]))]))]
                            ]));
            }),
          /* initialState */component$1[/* initialState */10],
          /* retainedProps */component$1[/* retainedProps */11],
          /* reducer */component$1[/* reducer */12],
          /* jsElementWrapped */component$1[/* jsElementWrapped */13]
        ];
}

var Secondary = /* module */[
  /* component */component$1,
  /* make */make$1
];

exports.S = S;
exports.component = component;
exports.make = make;
exports.Secondary = Secondary;
/* opacity Not a pure module */
