// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function let_(children, render) {
  return Curry._1(children, render);
}

exports.let_ = let_;
/* No side effect */
