// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function validate(rule, value, values) {
  if (rule) {
    return Curry._2(rule[0], value, values);
  } else {
    return value.length !== 0;
  }
}

function validateField(validations, value, values) {
  return List.fold_left((function (errors, param) {
                var match = validate(param[0], value, values);
                if (match) {
                  return errors;
                } else {
                  return List.append(errors, /* :: */[
                              param[1],
                              /* [] */0
                            ]);
                }
              }), /* [] */0, validations);
}

function validation(rules, get, data) {
  return List.fold_left((function (errors, param) {
                var field = param[0];
                var value = Curry._2(get, field, data);
                var fieldErrors = validateField(param[1], value, data);
                var match = List.length(fieldErrors) > 0;
                if (match) {
                  return List.append(errors, /* :: */[
                              /* tuple */[
                                field,
                                fieldErrors
                              ],
                              /* [] */0
                            ]);
                } else {
                  return errors;
                }
              }), /* [] */0, rules);
}

function FormComponent(Config) {
  var component = ReasonReact.reducerComponent("FormComponent");
  var make = function (initialState, rules, render, _children) {
    return /* record */[
            /* debugName */component[/* debugName */0],
            /* reactClassInternal */component[/* reactClassInternal */1],
            /* handedOffState */component[/* handedOffState */2],
            /* willReceiveProps */component[/* willReceiveProps */3],
            /* didMount */component[/* didMount */4],
            /* didUpdate */component[/* didUpdate */5],
            /* willUnmount */component[/* willUnmount */6],
            /* willUpdate */component[/* willUpdate */7],
            /* shouldUpdate */component[/* shouldUpdate */8],
            /* render */(function (param) {
                var send = param[/* send */3];
                var handleChange = function (field, value) {
                  return Curry._1(send, /* UpdateValues */[
                              field,
                              value
                            ]);
                };
                return Curry._1(render, /* record */[
                            /* form */param[/* state */1],
                            /* handleChange */handleChange
                          ]);
              }),
            /* initialState */(function (param) {
                return /* record */[
                        /* errors : [] */0,
                        /* values */initialState
                      ];
              }),
            /* retainedProps */component[/* retainedProps */11],
            /* reducer */(function (action, state) {
                var values = Curry._3(Config[/* update */0], action[0], action[1], state[/* values */1]);
                return /* Update */Block.__(0, [/* record */[
                            /* errors */validation(rules, Config[/* get */1], values),
                            /* values */values
                          ]]);
              }),
            /* jsElementWrapped */component[/* jsElementWrapped */13]
          ];
  };
  return /* module */[
          /* component */component,
          /* make */make
        ];
}

exports.validate = validate;
exports.validateField = validateField;
exports.validation = validation;
exports.FormComponent = FormComponent;
/* ReasonReact Not a pure module */
