// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Styles = require("../Styles.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Image$BsReactNative = require("bs-react-native/src/components/image.js");

var avatar = ReasonReact.element(undefined, undefined, Image$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, /* `Required */[
            202657151,
            require("../assets/matt-explosion-bw-small.png")
          ], Js_primitive.some(Styles.Media[/* avatar */0]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]));

var jsLogo = ReasonReact.element(undefined, undefined, Image$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, /* `Required */[
            202657151,
            require("../assets/js-explode.png")
          ], Js_primitive.some(Styles.Media[/* jsLogo */1]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]));

var reasonLogo = ReasonReact.element(undefined, undefined, Image$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, /* `Required */[
            202657151,
            require("../assets/reason-explode.png")
          ], Js_primitive.some(Styles.Media[/* reasonLogo */2]), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[]));

exports.avatar = avatar;
exports.jsLogo = jsLogo;
exports.reasonLogo = reasonLogo;
/* avatar Not a pure module */
