// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var State = require("../State.js");
var Utils = require("../Utils.js");
var Animatable = require("../Animatable.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Primatives$StyledFunctors = require("styled-functors/re/Primatives.js");
var TouchableOpacity$BsReactNative = require("bs-react-native/src/components/touchableOpacity.js");

var component = ReasonReact.statelessComponent("Menu");

function make(_children, navigation) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var handle = function (route) {
                Curry._1(State.ModalStore[/* updateState */3], false);
                return Curry._1(navigation[/* navigate */0], route);
              };
              return ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              true,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              undefined,
                              /* array */[
                                ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Box[/* make */0], [
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          /* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      /* right */-379319332,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      undefined,
                                                      /* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Box[/* make */0], [
                                                                  /* `p */[
                                                                    112,
                                                                    6
                                                                  ],
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  undefined,
                                                                  /* array */[ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_evt) {
                                                                                  return Curry._1(State.ModalStore[/* updateState */3], false);
                                                                                }), undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        undefined,
                                                                                        /* array */[Utils.str("Close")]
                                                                                      ]))]))]
                                                                ]))]
                                                    ]))]
                                        ])),
                                ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                                          undefined,
                                          /* `mt */[
                                            24423,
                                            4
                                          ],
                                          undefined,
                                          /* centerX */434500835,
                                          true,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          undefined,
                                          /* array */[
                                            ReasonReact.element(undefined, undefined, Animatable.make("zoomIn", undefined, 400)(/* array */[ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_evt) {
                                                                    return handle(/* Cover */0);
                                                                  }), undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                          /* `py */[
                                                                            25097,
                                                                            6.0
                                                                          ],
                                                                          undefined,
                                                                          /* `size */[
                                                                            -866934591,
                                                                            3.0
                                                                          ],
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          /* array */[Utils.str("Cover")]
                                                                        ]))]))])),
                                            ReasonReact.element(undefined, undefined, Animatable.make("zoomIn", 100, 300)(/* array */[ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (_evt) {
                                                                    return handle(/* Story */1);
                                                                  }), undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                          /* `py */[
                                                                            25097,
                                                                            6.0
                                                                          ],
                                                                          undefined,
                                                                          /* `size */[
                                                                            -866934591,
                                                                            3.0
                                                                          ],
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          /* array */[Utils.str("Story")]
                                                                        ]))]))])),
                                            ReasonReact.element(undefined, undefined, Animatable.make("zoomIn", 200, 300)(/* array */[ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (param) {
                                                                    return handle(/* Abilities */2);
                                                                  }), undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                          /* `py */[
                                                                            25097,
                                                                            6.0
                                                                          ],
                                                                          undefined,
                                                                          /* `size */[
                                                                            -866934591,
                                                                            3.0
                                                                          ],
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          /* array */[Utils.str("Abilities")]
                                                                        ]))]))])),
                                            ReasonReact.element(undefined, undefined, Animatable.make("zoomIn", 300, 300)(/* array */[ReasonReact.element(undefined, undefined, TouchableOpacity$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, (function (param) {
                                                                    return handle(/* Conclusion */3);
                                                                  }), undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                          /* `py */[
                                                                            25097,
                                                                            6.0
                                                                          ],
                                                                          undefined,
                                                                          /* `size */[
                                                                            -866934591,
                                                                            3.0
                                                                          ],
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          undefined,
                                                                          /* array */[Utils.str("Conclusion")]
                                                                        ]))]))]))
                                          ]
                                        ]))
                              ]
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
