// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var ReactNativeAnimatable = require("react-native-animatable");

function make(animation, delay, duration) {
  var partial_arg = {
    animation: animation,
    delay: Js_null_undefined.fromOption(delay),
    duration: Js_null_undefined.fromOption(duration)
  };
  var partial_arg$1 = ReactNativeAnimatable.View;
  return (function (param) {
      return ReasonReact.wrapJsForReason(partial_arg$1, partial_arg, param);
    });
}

exports.make = make;
/* ReasonReact Not a pure module */
