// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Style$BsReactNative = require("bs-react-native/src/style.js");
var ReactNativeGlobalProps = require("react-native-global-props");

function make(param) {
  ReactNativeGlobalProps.setCustomText({
        underlineColorAndroid: "#00000000",
        style: Style$BsReactNative.style(/* :: */[
              Style$BsReactNative.fontFamily("Secular One"),
              /* [] */0
            ])
      });
  ReactNativeGlobalProps.setCustomTextInput({
        underlineColorAndroid: "#00000000"
      });
  return /* () */0;
}

exports.make = make;
/* Style-BsReactNative Not a pure module */
