// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function CreateStore(C) {
  var state = /* record */[/* contents */C[/* value */1]];
  var subscriptions = /* record */[/* contents : array */[]];
  var addSubscription = function (f) {
    subscriptions[0] = subscriptions[0].concat(/* array */[f]);
    return (function (param) {
        subscriptions[0] = subscriptions[0].filter((function (sub) {
                return sub !== f;
              }));
        return /* () */0;
      });
  };
  var updateState = function (newStateOpt) {
    var newState = newStateOpt !== undefined ? Js_primitive.valFromOption(newStateOpt) : C[/* value */1];
    state[0] = newState;
    subscriptions[0].forEach((function (f) {
            return Curry._1(f, newState);
          }));
    return /* () */0;
  };
  var component = ReasonReact.reducerComponent(C[/* debugName */0] + "StoreConsumer");
  var make = function (render, _children) {
    return /* record */[
            /* debugName */component[/* debugName */0],
            /* reactClassInternal */component[/* reactClassInternal */1],
            /* handedOffState */component[/* handedOffState */2],
            /* willReceiveProps */component[/* willReceiveProps */3],
            /* didMount */(function (param) {
                var send = param[/* send */3];
                return Curry._1(param[/* onUnmount */4], addSubscription((function (newState) {
                                  return Curry._1(send, /* ChangeState */[newState]);
                                })));
              }),
            /* didUpdate */component[/* didUpdate */5],
            /* willUnmount */component[/* willUnmount */6],
            /* willUpdate */component[/* willUpdate */7],
            /* shouldUpdate */component[/* shouldUpdate */8],
            /* render */(function (param) {
                return Curry._1(render, param[/* state */1]);
              }),
            /* initialState */(function (param) {
                return state[0];
              }),
            /* retainedProps */component[/* retainedProps */11],
            /* reducer */(function (action, _state) {
                return /* Update */Block.__(0, [action[0]]);
              }),
            /* jsElementWrapped */component[/* jsElementWrapped */13]
          ];
  };
  var Consumer = /* module */[
    /* component */component,
    /* make */make
  ];
  return /* module */[
          /* state */state,
          /* subscriptions */subscriptions,
          /* addSubscription */addSubscription,
          /* updateState */updateState,
          /* Consumer */Consumer
        ];
}

exports.CreateStore = CreateStore;
/* ReasonReact Not a pure module */
