// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Stature = require("./Stature.js");

var debugName = "ModalStore";

var ModalConfig = /* module */[
  /* value */false,
  /* debugName */debugName
];

var ModalStore = Stature.CreateStore([
      debugName,
      false
    ]);

exports.ModalConfig = ModalConfig;
exports.ModalStore = ModalStore;
/* ModalStore Not a pure module */
