// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");

var purple = "rgba(120, 49, 162, 1.0)";

var white = "white";

var black = "black";

var Palatte = /* module */[
  /* purple */purple,
  /* white */white,
  /* black */black
];

var purple$1 = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.color(/* String */Block.__(0, [purple])),
      /* [] */0
    ]);

var white$1 = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.color(/* String */Block.__(0, [white])),
      /* [] */0
    ]);

var purpleBg = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, [purple])),
      /* [] */0
    ]);

var blackBg = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.backgroundColor(/* String */Block.__(0, [black])),
      /* [] */0
    ]);

var Color = /* module */[
  /* purple */purple$1,
  /* white */white$1,
  /* purpleBg */purpleBg,
  /* blackBg */blackBg
];

var textCenter = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.textAlign(/* Center */3),
      /* [] */0
    ]);

var fontWeightNormal = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.fontWeight(/* Normal */-453122489),
      /* [] */0
    ]);

var fontWeightBold = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.fontWeight(/* Bold */737455525),
      /* [] */0
    ]);

var fontItalic = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.fontStyle(/* Italic */1),
      /* [] */0
    ]);

var fontBoldItalic = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.fontWeight(/* _900 */1056354170),
      /* :: */[
        Style$BsReactNative.fontStyle(/* Italic */1),
        /* [] */0
      ]
    ]);

var opacity50 = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.opacity(/* Float */Block.__(0, [50])),
      /* [] */0
    ]);

var opacity30 = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.opacity(/* Float */Block.__(0, [30])),
      /* [] */0
    ]);

var Font = /* module */[
  /* textCenter */textCenter,
  /* fontWeightNormal */fontWeightNormal,
  /* fontWeightBold */fontWeightBold,
  /* fontItalic */fontItalic,
  /* fontBoldItalic */fontBoldItalic,
  /* opacity50 */opacity50,
  /* opacity30 */opacity30
];

var avatar = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.width(/* Pt */Block.__(0, [250])),
      /* :: */[
        Style$BsReactNative.height(/* Pt */Block.__(0, [175])),
        /* [] */0
      ]
    ]);

var jsLogo = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.width(/* Pt */Block.__(0, [150])),
      /* :: */[
        Style$BsReactNative.height(/* Pt */Block.__(0, [115])),
        /* [] */0
      ]
    ]);

var reasonLogo = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.width(/* Pt */Block.__(0, [150])),
      /* :: */[
        Style$BsReactNative.height(/* Pt */Block.__(0, [115])),
        /* [] */0
      ]
    ]);

var Media = /* module */[
  /* avatar */avatar,
  /* jsLogo */jsLogo,
  /* reasonLogo */reasonLogo
];

exports.Palatte = Palatte;
exports.Color = Color;
exports.Font = Font;
exports.Media = Media;
/* purple Not a pure module */
