// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Cover = require("../shared/screens/Cover.js");
var Story = require("../shared/screens/Story.js");
var Abilities = require("../shared/screens/Abilities.js");
var Conclusion = require("../shared/screens/Conclusion.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var SwitchNavigatorWeb$BsReactNavigation = require("bs-react-navigation/src/SwitchNavigatorWeb.bs.js");

function getScreen(route, navigation) {
  switch (route) {
    case 0 : 
        return /* tuple */[
                ReasonReact.element(undefined, undefined, Cover.make(navigation, /* array */[])),
                {
                  title: "Cover"
                }
              ];
    case 1 : 
        return /* tuple */[
                ReasonReact.element(undefined, undefined, Story.make(navigation, /* array */[])),
                {
                  title: "Story"
                }
              ];
    case 2 : 
        return /* tuple */[
                ReasonReact.element(undefined, undefined, Abilities.make(navigation, /* array */[])),
                {
                  title: "Abilities"
                }
              ];
    case 3 : 
        return /* tuple */[
                ReasonReact.element(undefined, undefined, Conclusion.make(navigation, /* array */[])),
                {
                  title: "Conclusion"
                }
              ];
    
  }
}

var Stack = SwitchNavigatorWeb$BsReactNavigation.Create(/* module */[
      /* initialRoute : Cover */0,
      /* getScreen */getScreen
    ]);

var app = Stack[/* render */11];

exports.Stack = Stack;
exports.app = app;
/* Stack Not a pure module */
