// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Btn = require("../components/Btn.js");
var Menu = require("../components/Menu.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Icons = require("../components/Icons.js");
var State = require("../State.js");
var Utils = require("../Utils.js");
var Epitath = require("../components/Epitath.js");
var MenuButton = require("../components/MenuButton.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactNative = require("react-native");
var Primatives$StyledFunctors = require("styled-functors/re/Primatives.js");

var component = ReasonReact.statelessComponent("Contact");

function make(navigation, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return Epitath.let_((function (children) {
                            return ReasonReact.element(undefined, undefined, Curry._2(State.ModalStore[/* Consumer */4][/* make */1], children, /* array */[]));
                          }), (function (showModal) {
                            if (showModal) {
                              return ReasonReact.element(undefined, undefined, Menu.make(/* array */[], navigation));
                            } else {
                              return ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              true,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              /* array */[
                                                ReasonReact.element(undefined, undefined, MenuButton.make((function (param) {
                                                            return Curry._1(State.ModalStore[/* updateState */3], true);
                                                          }), /* array */[])),
                                                ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                                                          /* `px */[
                                                            25096,
                                                            8
                                                          ],
                                                          undefined,
                                                          undefined,
                                                          /* centerX */434500835,
                                                          true,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          /* array */[
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      undefined,
                                                                      /* `mt */[
                                                                        24423,
                                                                        20
                                                                      ],
                                                                      /* `size */[
                                                                        -866934591,
                                                                        1.7
                                                                      ],
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[Utils.str("Coming Soon...")]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      undefined,
                                                                      /* `mt */[
                                                                        24423,
                                                                        8
                                                                      ],
                                                                      /* `size */[
                                                                        -866934591,
                                                                        4.5
                                                                      ],
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[Utils.str("YOUR PROJECT HERE")]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Box[/* make */0], [
                                                                      /* `py */[
                                                                        25097,
                                                                        8
                                                                      ],
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[ReasonReact.element(undefined, undefined, Icons.make("bolt", 30, "gray")(/* array */[]))]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Btn.make(/* array */[], (function (_evt) {
                                                                        ReactNative.Linking.openURL("mailto:matt@hew.tools").then((function (param) {
                                                                                return Promise.resolve((console.log("opened link to email"), /* () */0));
                                                                              }));
                                                                        return /* () */0;
                                                                      }), "Let's Chat!")),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Box[/* make */0], [
                                                                      undefined,
                                                                      /* `mt */[
                                                                        24423,
                                                                        4
                                                                      ],
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Btn.Secondary[/* make */1](/* array */[], (function (_evt) {
                                                                        ReactNative.Linking.openURL("https://github.com/hew/hew.tools").then((function (param) {
                                                                                return Promise.resolve((console.log("opened link to Github"), /* () */0));
                                                                              }));
                                                                        return /* () */0;
                                                                      }), "View Source")),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      undefined,
                                                                      /* `mt */[
                                                                        24423,
                                                                        20
                                                                      ],
                                                                      undefined,
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    1.0
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("Overengineered ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    0.8
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("and ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    1.0
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("Javascript & Reasonml ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    0.8
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("present ")]
                                                                                ]))
                                                                      ]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  /* `mt */[
                                                                                    24423,
                                                                                    20
                                                                                  ],
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    1.0
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("Personal Site: 3")]
                                                                                ]))]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  /* `mt */[
                                                                                    24423,
                                                                                    20
                                                                                  ],
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    0.8
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("In Association with ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  /* `mt */[
                                                                                    24423,
                                                                                    20
                                                                                  ],
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    1.0
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("React Native Pictures ")]
                                                                                ]))
                                                                      ]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  /* `mt */[
                                                                                    24423,
                                                                                    20
                                                                                  ],
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    0.8
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("a ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  /* `mt */[
                                                                                    24423,
                                                                                    20
                                                                                  ],
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    1.0
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("Open Source Tech  ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  /* `mt */[
                                                                                    24423,
                                                                                    20
                                                                                  ],
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    0.8
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("Production ")]
                                                                                ]))
                                                                      ]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    0.8
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("Starring ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    1.0
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("Matthew Jones  ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    0.8
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("and Introducing ")]
                                                                                ])),
                                                                        ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* `size */[
                                                                                    -866934591,
                                                                                    1.0
                                                                                  ],
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  undefined,
                                                                                  /* array */[Utils.str("'The Client' ")]
                                                                                ]))
                                                                      ]
                                                                    ]))
                                                          ]
                                                        ]))
                                              ]
                                            ]));
                            }
                          }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
