// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Btn = require("../components/Btn.js");
var Menu = require("../components/Menu.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Media = require("../components/Media.js");
var State = require("../State.js");
var Utils = require("../Utils.js");
var Epitath = require("../components/Epitath.js");
var Animatable = require("../Animatable.js");
var MenuButton = require("../components/MenuButton.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Primatives$StyledFunctors = require("styled-functors/re/Primatives.js");

var copy = "He's a generalist mad scientist on a mission: type-safe, cross-platform UI code.";

var copy2 = "An ex-copywriter, his programming started one fateful night when he ate an unassuming jar of radioactive hummus.";

var component = ReasonReact.statelessComponent("Story");

function make(navigation, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              return Epitath.let_((function (children) {
                            return ReasonReact.element(undefined, undefined, Curry._2(State.ModalStore[/* Consumer */4][/* make */1], children, /* array */[]));
                          }), (function (showModal) {
                            if (showModal) {
                              return ReasonReact.element(undefined, undefined, Menu.make(/* array */[], navigation));
                            } else {
                              return ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              true,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              undefined,
                                              /* array */[
                                                ReasonReact.element(undefined, undefined, MenuButton.make((function (param) {
                                                            return Curry._1(State.ModalStore[/* updateState */3], true);
                                                          }), /* array */[])),
                                                ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Flex[/* make */0], [
                                                          /* `px */[
                                                            25096,
                                                            8
                                                          ],
                                                          undefined,
                                                          undefined,
                                                          /* centerX */434500835,
                                                          true,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          undefined,
                                                          /* array */[
                                                            ReasonReact.element(undefined, undefined, Animatable.make("tada", undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Box[/* make */0], [
                                                                                /* `py */[
                                                                                  25097,
                                                                                  8.0
                                                                                ],
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                undefined,
                                                                                /* array */[Media.avatar]
                                                                              ]))])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      /* `py */[
                                                                        25097,
                                                                        4
                                                                      ],
                                                                      undefined,
                                                                      /* `size */[
                                                                        -866934591,
                                                                        1.7
                                                                      ],
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[Utils.str(copy)]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.T[/* make */0], [
                                                                      /* `py */[
                                                                        25097,
                                                                        4
                                                                      ],
                                                                      undefined,
                                                                      /* `size */[
                                                                        -866934591,
                                                                        1.7
                                                                      ],
                                                                      undefined,
                                                                      true,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[Utils.str(copy2)]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Curry.app(Primatives$StyledFunctors.Box[/* make */0], [
                                                                      undefined,
                                                                      /* `mt */[
                                                                        24423,
                                                                        8.0
                                                                      ],
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      undefined,
                                                                      /* array */[]
                                                                    ])),
                                                            ReasonReact.element(undefined, undefined, Btn.make(/* array */[], (function (_evt) {
                                                                        return Curry._1(navigation[/* navigate */0], /* Abilities */2);
                                                                      }), "See Abilities"))
                                                          ]
                                                        ]))
                                              ]
                                            ]));
                            }
                          }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.copy = copy;
exports.copy2 = copy2;
exports.component = component;
exports.make = make;
/* component Not a pure module */
